config/routes.rb
Rails.application.routes.draw do
  get 'user/admin_user'
  devise_for :users
  get "up" => "rails/health#show", as: :rails_health_check
  
  # action cable
  mount ActionCable.server => '/cable'

  resources :products do
    member do
      match '/destroy', action: :destroy, via: [:get, :delete], as: :destroy

      match 'favorite', action: :favorite, via: [:get, :post], as: :favorite
    end

    resources :favorites
    resources :comments, only: [:create, :destroy]
    collection do
      get 'load_products'
    end
  end

  resources :activity_logs

  resources :carts do
    member do
      # actions new, add product, remove product
      get '/new_cart', to: 'carts#new', as: :new_cart # Cart
      match '/add_to_cart/product_id', action: :add_to_cart, via: [:get, :post], as: :add_to_cart # CartItem, Cart, and Product
      match '/remove_product_from_cart/:product_id', action: :remove_product_from_cart, via: [:get, :delete], as: :remove_product_from_cart
      
      # update quantity, and downgrade quantity(if > 1)
      match '/update_quantity/:product_id', action: :update_quantity, via: [:get, :patch], as: :update_quantity
      match '/downgrade_quantity/:product_id', action: :downgrade_quantity, via: [:get, :patch], as: :downgrade_quantity
      
      # checkout and make empty again cart of user BEFORE completed the order.
      get '/checkout', to: 'carts#checkout', as: :checkout # CartItem
      match 'destroy_all_items', via: [:get, :post]
    end
  end

  resources :users do
    member do
      match 'add_balance', action: :add_balance, via: [:get, :post], as: :add_balance
    end
  end
  
  match '/admin_user', to: 'users#admin_user', via: [:get, :post]
  
  resources :home do
    member do
      get '/history/', to: 'home#history', as: :history
      get '/user/', to: 'home#user', as: :user
      get '/favorite/', to: 'home#favorite', as: :favorite
    end
  end

  namespace :admin do

    get 'charts', to: 'home#charts', as: :charts
    root "home#index"
  end

  # Defines the root path route ("/")
  root "home#about"
end

app/views/shared/_footer.html.erb
<header class="text-center">
  oi
</header>

app/views/shared/_navbar.html.erb
<header>
    <a href="<%= root_path %>" class="logo">
    <img src="https://media.istockphoto.com/id/649490870/photo/world-icon-premium-blue-round-button.jpg?s=2048x2048&w=is&k=20&c=FQmvmt7P72RrVl59RQ14xEGmSzSDcUJ9A8iwQRbsg4U="
    style="width: 50px; height: auto; border-radius: 50%; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);">
    </a>   
    <%# Navbar Links_to %>
    <%# Icons %>
    <div class="icons">
      <div class="dropdown">
        <button class="#" type="#" id="bi bi-bag-check" data-bs-toggle="dropdown" aria-expanded="false">
          <i class="bi bi-person"></i>
        </button>
      <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
      




        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">

  

          <% if user_signed_in? %>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete, data: { turbo_method: :delete }, class: "dropdown-item" %></li>
            <li><%= link_to "Profile", user_home_path(current_user), class: "dropdown-item" %></li>



            
            
            <li><hr class="dropdown-divider"></li>
           
            <li><%= link_to "Activities", "http://127.0.0.1:3000/activity_logs", class: "dropdown-item" %></li>

            <% if user_signed_in? && current_user.admin? %>
            <li><hr class="dropdown-divider"></li>
            
              <li><%= link_to "Admin Board", admin_root_path, class: "dropdown-item" %></li>
            <% end %>
          <% else %>
 
       
            <li><%= link_to "New? Sign In", new_user_registration_path, class: "dropdown-item" %></li>
          <% end %>
          <% unless user_signed_in? %>
            <%# Portfolio Button for Jobs/etc %>
            <li><%= link_to "Portfolio Admin", admin_user_path, class: "dropdown-item" %></li>
          <% end %>
        </ul>
      </div>

      <%# History Section %>
      <% if current_user.present? %>
        <a href="<%= history_home_path(current_user) %>"><i class="bi bi-bag-check"></i></a>

        <a href="http://127.0.0.1:3000/products"><i class="bi bi-bag-heart"></i></a>


      <% else %>
        <a href="<%= new_user_session_path %>"><i class="bi bi-bag-check"></i></a>
      <% end %>
      
      <%# Admin Section %>
      <% if current_user.present? %>
 
              <% else %>
        <a href="<%= new_user_session_path %>"><i class="bi bi-bag-heart"></i></a>
      <% end %>


      <%# Create a new Product Section %>
      <% if user_signed_in? %>
        <a href="<%= new_product_path %>"><i class="bi bi-box"></i></a>
      <% end %>

            <a href="http://127.0.0.1:3000" 
         style="text-decoration: none; color: #333; display: flex; align-items: center; gap: 8px;">
        <span style="font-size: 18px; display: inline-block;">
          <i class="bi bi-house-fill"></i>
        </span> 
      
      </a>
    </div>


</header>